basePath: /emulate
definitions:
  main.EmulateRequest:
    properties:
      boc:
        example: te6ccgEBAQEAAgAAAA==
        type: string
      ignore_chksig:
        example: false
        type: boolean
    type: object
info:
  contact: {}
  description: TON Emulate API emulates trace by external message.
  title: TON Emulate API
  version: 0.0.1
paths:
  /v1/emulateTrace:
    post:
      consumes:
      - application/json
      description: Emulate trace by external message.
      parameters:
      - description: External Message BOC
        in: body
        name: boc
        required: true
        schema:
          $ref: '#/definitions/main.EmulateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Emulate trace by external message
      tags:
      - emulate
swagger: "2.0"
